#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# sync gentoo cache
"${TOPDIR}"/scripts/sync-gentoo-cache

# sync local cache
"${TOPDIR}"/scripts/sync-local-cache

# output simplified eix-diff
export DIFF_FORMAT_ALL_NEW=
export CHAR_UPGRADE="\\>"
export CHAR_DOWNGRADE="\\<"
export DIFF_FORMATLINE_INSTALLEDVERSIONS=

echo
echo "upstream is more up to date with these packages:"
echo

eix-diff ${TOPDIR}/eix.cache.{local,gentoo} | \
	grep -v 'Diffing database' | \
	sed 's/{tbz2}//g' | \
	sed '/^\[<\]   ==/d' | \
	sed '/^\[<>\]  ==/d' | \
	sed '/^\[><\]  ==/d' | \
	sed '/   <</d' | \
	sed '/(\(.*\) -> .*\1)/d' | \
	grep -v '== virtual/ruby-ssl' | \
	grep -v '== virtual/rubygems'

echo
echo "downstream is more up to date with these packages:"
echo

eix-diff ${TOPDIR}/eix.cache.{local,gentoo} | \
	grep -v 'Diffing database' | \
	sed 's/{tbz2}//g' | \
	sed '/^\[>\]   ==/d' | \
	sed '/^\[<>\]  ==/d' | \
	sed '/^\[><\]  ==/d' | \
	sed 's/\[<\]   <</      <</g' | \
	sed 's/~//g' | \
	sed '/(\(.*\) -> .*\1)/d'
