#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

pushd "${TOPDIR}" > /dev/null

# mangle user input
for atom in "$@"; do
	catpkg="${atom#=}"
	catpkg="${catpkg%-[0-9]*}"

	if [[ ! -d ${catpkg} ]]; then
		eerror "Atom ${catpkg} does not exist"
		exit 1
	fi

	git reset HEAD ${catpkg}
	rm -rf ${catpkg}
	git checkout ${catpkg}
done
