#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

pushd "${TOPDIR}" > /dev/null

if [[ $# -eq 0 ]]; then
	export SKIP_REPOMAN=1
	export SKIP_DIFF=1
	set -- $(find . -name '*.ebuild' -printf '%h\n' | sed 's:^\./\?::g' | sort -u)
fi

# expand atoms first
for atom in "$@"; do
	# mangle user input
	catpkg="${atom#=}"
	catpkg="${catpkg%-[0-9]*}"

	echo
	is_blacklisted ${catpkg} && continue

	if [[ ! -d ${GENTOO_CACHE}/${catpkg} ]]; then
		echo "!!! ${catpkg} not in upstream repository, leaving it alone ..."
		continue
	fi

	# expand atom
	atoms=$("${TOPDIR}"/profiles/releases/zentoo/eupdate.expand.sh ${atom})

	rm -rf ${catpkg}

	for atom in ${atoms}; do
		"${TOPDIR}"/scripts/ecopy "${atom}"
	done

	if [[ ${SKIP_DIFF} -eq 1 ]]; then
		continue
	fi

	if [[ "$(git diff --cached ${catpkg})" != "" ]]; then
		git diff --cached ${catpkg}
	fi
done

if [[ -n ${SKIP_REPOMAN} ]]; then
	repoman manifest
	git add -A
fi
