#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

pushd "${TOPDIR}" > /dev/null

for atom in "$@"; do
	# mangle user input
	catpkg="${atom#=}"
	catpkg="${catpkg%-[0-9]*}"

	if [[ -d ${GENTOO_CACHE}/${catpkg} ]]; then
		rm -rf ${catpkg}
		"${TOPDIR}"/scripts/ecopy "${atom}"
		git diff --cached ${catpkg}
	else
		echo "!!! ${catpkg} not in upstream repository, leaving it alone ..."
	fi
done
