#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# sync gentoo repository
"${TOPDIR}"/scripts/sync-gentoo-cache

# copy the files
for file in "$@"; do
	mkdir -p "$(dirname "${TOPDIR}/${file}")"
	cp -v "${GENTOO_CACHE}/${file}" "${file}"
done
