#!/bin/bash

set -e

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

setup_portdir

pushd "${TOPDIR}" > /dev/null

# pull latest changes
git fetch origin
git reset --hard @{upstream}
git clean -fd

# generate manifests for distribution and repoman sanity
repoman manifest

# setup make.conf for egencache
mkdir -p "${TOPDIR}"/etc
cat <<EOF > "${TOPDIR}"/etc/make.conf
PORTDIR=${PORTDIR}
PORTDIR_OVERLAY="${PORTDIR_OVERLAY}"
EOF

# update the metadata and use.local.desc files in the repo
egencache --update --update-use-local-desc \
	--config="${TOPDIR}" --jobs=3 \
	--repo=$(<"${TOPDIR}"/profiles/repo_name)

# update timestamps
touch metadata/timestamp.chk
