#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

set -e

setup_portdir

# pull latest changes if running on mirror
if [[ "${TOPDIR}" == "/var/cache/mirror/zentoo/portage" ]]; then
	git fetch origin
	git reset --hard @{upstream}
	git clean -fd
fi

# generate manifests for distribution and repoman sanity
repoman manifest

# setup make.conf for egencache
mkdir -p "${TOPDIR}"/etc
cat <<EOF > "${TOPDIR}"/etc/make.conf
PORTDIR=${PORTDIR}
PORTDIR_OVERLAY="${PORTDIR_OVERLAY}"
EOF

# update the metadata and use.local.desc files in the repo
egencache --update --update-use-local-desc \
	--config="${TOPDIR}" --jobs=3 \
	--repo=$(<"${TOPDIR}"/profiles/repo_name)

# update timestamps
touch metadata/timestamp.chk
