#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# sync local cache
"${TOPDIR}"/scripts/generate-cache

# output simplified eix-diff
while read atom; do
	if [[ ! -d ${atom} ]]; then
		continue
	fi

	if grep -q ${atom} -r "${TOPDIR}"/metadata/cache; then
		continue
	fi

	echo ${atom}
done < <(
	eix --cache-file "${TOPDIR}"/eix.cache.${REPO_NAME} --pure-packages --only-names
)
