#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# sync local cache first
#"${TOPDIR}"/scripts/sync-local-cache

echo "Number of packages: $(leix -cn --only-names|wc -l)"
echo
echo "EAPI distribution:"
echo
echo "  COUNT EAPI"

sed 's/EAPI=//p;d' metadata/md5-cache/*/* | sort -r | uniq -c
