#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

rsync -a --del \
	--exclude=timestamp* \
	--exclude=/.cvsignore \
	--exclude=/cache \
	--exclude=/md5-cache \
	--exclude=/news/200* \
	--exclude=/news/2010* \
	--exclude=/news/2011* \
	--exclude=/news/2012* \
	"${GENTOO_CACHE}"/metadata/ \
	"${TOPDIR}"/metadata/
