#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# update gentoo cache
export PORTDIR="${GENTOO_CACHE}"
export PORTDIR_OVERLAY=

tschk="${PORTDIR}"/metadata/timestamp.chk

if [[ ! -e "${tschk}" || $(find "${tschk}" -mmin +180) != "" ]]; then
	rsync --verbose \
		--recursive \
		--links \
		--safe-links \
		--perms \
		--times \
		--compress \
		--force \
		--whole-file \
		--delete \
		--exclude=/distfiles \
		--exclude=/local \
		--exclude=/packages \
		rsync://rsync.de.gentoo.org/gentoo-portage/ \
		"${PORTDIR}"/
fi

# update gentoo eix cache
if test "${tschk}" -nt "${GENTOO_EIX_CACHE}"; then
	./scripts/eix-update
fi
