#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)
source "${TOPDIR}"/scripts/common.sh

# sync gentoo repository
"${TOPDIR}"/scripts/sync-gentoo-cache

rsync -a --del \
	--exclude=/linux-image.eclass \
	--exclude=/xorg-2.eclass \
	${GENTOO_CACHE}/eclass/ \
	${TOPDIR}/eclass/

cd ${TOPDIR}

git clean -fd eclass/
sed -i -e '/\$Header:/d' eclass/*.eclass
